### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by I4WNICT**

### CODE REVIEW

**Comment by ricoms** [comment]
Hi @I4WNICT, the master is not supposed to receive content push. Are these website admin modifications that you intend?

**Comment by ricoms** [comment]
From what I see on the files and modifications, this PR looks like a mistake. Is that correct @I4WNICT ? @cmihaigabriel 

Do you need help?

**Comment by I4WNICT** [comment]
Dear Ricardo,

we use two account (1) I4WNICT, and (2) minhson.dao74@gmail.com to access the MediaEval.

Currently, we mostly modify our page using I4WNICT, and we do not have the right to access master level. So, all our modifications are saved in branch level.

If it is possible, I wonder if you could grant another access right to the account minhson.dao74@gmail.com.

Regards,
________________________________

**Comment by ricoms** [comment]
Hello @I4WNICT .

I see that you alread made PR to the `gh-page` branch. Thanks for that.

Sorry for the confusion, but `master` branch is not made to receive direct Pull requests or even pushes.

**Pull request closed without merging**
